### ISSUE TITLE
## Todo list

### ISSUE THREAD

**Issue by TheC0mposer** [TheC0mposer/MyFirstRepository#3]
### Becoming a Full Stack Engineer - What to learn
- [ ] UI/UX (Standard Desktop & Mobile & Swipe / Pinch)
- [x] Sketch & Pixelmator / Vectormator - UI/UX  Wireframing

---
- [x] Html5 - Markup Language
- [x] CSS3 - Frontend Stylesheets - Sass - Gulp - Elixir - Compass
- [ ] D3.js - Graphics Library
- [x] Javascript - Typescript
- [x] Ajax  - Jquery & plugins
- [x] Angular.js  - Frontend Framework - Ionic 2 - Creator
- [ ] Yeoman - Structuring
- [ ] Kendo UI - Html & Javascript Micro Framework
- [ ] Browserfiy - Javascript Modules
- [ ] Protractor - Testing
- [x] WebStorm - Frontend IDE

---
- [x] PhP
- [x] Laravel - Backend Framework - Homestead  - Virtualbox & Vagrant
- [x] Homestead - Laravel Package
- [x] RESTful MCV - Project Architecture Design
- [ ] Forge
- [ ] Envoyer
- [x] PhPStorm - Backend IDE

---
- [x] MySQL - Query Language - Relational Database Design
- [ ] Prometheus & Grafana - MySQL Indexing & Performance Tuning 
- [ ] Datagrip - Database IDE

---
- [x] Terminal & Linux - Bash Shell - Bower & Composer & Grunt & Homebrew - npm
- [x] Git - VCS - Git-Flow
- [x] Github

**Comment by TheC0mposer** [comment]
This is a list of everything I know and currently plan to know by July 2016. Boxes will be checked upon completion. Generally a box is checked every few weeks, depending on what it entitles. Me being a self taught programmer, I don't check a box simply because I received a passing grade; The only way a box is ever checked is if I believe I comprehend the topic enough to teach others from scratch.
